"""
Pydantic schemas for Gemini API structured responses.

Defines the expected JSON structures for topic articles and podcast scripts,
ensuring runtime validation and type safety.
"""

import html
import re
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class TopicResponse(BaseModel):
    """
    Structured response for a full topic/article generated by Gemini.

    Contains all parts of a publishable post: title, introduction, body
    paragraphs, conclusion, and a separate quote.
    """

    title: str = Field(..., min_length=1, description="The main title of the topic/article")
    introduction: str = Field(
        ..., min_length=1, description="An engaging opening paragraph (2-4 sentences)"
    )
    body: List[str] = Field(
        ..., min_length=1, description="Main content paragraphs, typically 3-5 paragraphs"
    )
    conclusion: str = Field(
        ..., min_length=1, description="A closing paragraph summarizing the key message"
    )
    quote_text: str = Field(..., min_length=1, description="An inspiring or relevant quote")
    quote_author: Optional[str] = Field(
        None, description="Author of the quote, if known or attributable"
    )

    @field_validator("quote_author", mode="before")
    @classmethod
    def normalize_quote_author(cls, v: str) -> Optional[str]:
        """Convert empty strings to None."""
        if isinstance(v, str) and not v.strip():
            return None
        return v

    def to_full_text(self) -> str:
        """
        Concatenate all parts into a single plain text string.

        Returns:
            Formatted text suitable for display or logging.
        """
        parts = [
            self.title,
            "",
            self.introduction,
            "",
            "\n\n".join(self.body),
            "",
            self.conclusion,
            "",
            f'"{self.quote_text}"',
        ]
        if self.quote_author:
            parts.append(f"-- {self.quote_author}")
        return "\n".join(parts)

    def to_telegram_html(self, max_length: Optional[int] = None) -> str:
        """
        Format the topic as HTML for Telegram messages.

        Args:
            max_length: Optional maximum length of the output. If exceeded,
                        the text is truncated gracefully at word boundaries.

        Returns:
            HTML string with bold title, italic quote, etc. Special HTML
            characters in the content are automatically escaped.
        """
        # Escape all user-provided text to prevent HTML injection
        title = html.escape(self.title)
        intro = html.escape(self.introduction)
        conclusion = html.escape(self.conclusion)
        quote_text = html.escape(self.quote_text)
        quote_author = html.escape(self.quote_author) if self.quote_author else None

        # Escape each body paragraph and wrap in <p> tags
        body_paragraphs = [f"<p>{html.escape(p)}</p>" for p in self.body]
        body_html = "\n\n".join(body_paragraphs)

        quote_html = f'<i>"{quote_text}"</i>'
        if quote_author:
            quote_html += f" -- <b>{quote_author}</b>"

        html_content = f"""
<b>{title}</b>

{intro}

{body_html}

{conclusion}

{quote_html}
""".strip()

        # Apply truncation if requested
        if max_length is not None and len(html_content) > max_length:
            # Truncate at word boundary near the limit
            truncated = html_content[:max_length]
            # Try to cut at last space or newline
            last_space = max(
                truncated.rfind(" "),
                truncated.rfind("\n"),
                truncated.rfind(">"),
            )
            if last_space > max_length // 2:  # Only if we keep enough content
                truncated = truncated[:last_space]
            html_content = truncated + "..."

        return html_content


class PodcastScript(BaseModel):
    """
    Structured response for a short podcast script generated by Gemini.

    Designed for Edge-TTS audio generation; total length should be
    approximately 90-120 seconds when spoken.
    """

    title: str = Field(..., min_length=1, description="Podcast episode title (can match main topic)")
    intro: str = Field(
        ..., min_length=1, description="Brief introduction, approximately 20-40 words"
    )
    segments: List[str] = Field(
        ...,
        min_length=2,
        max_length=4,
        description="2 to 4 key points or paragraphs for the podcast body",
    )
    outro: str = Field(
        ..., min_length=1, description="Brief conclusion, approximately 20-40 words"
    )

    @field_validator("segments")
    @classmethod
    def validate_segments_count(cls, v: List[str]) -> List[str]:
        """Ensure segments list contains between 2 and 4 items."""
        if len(v) < 2:
            raise ValueError("segments must contain at least 2 items")
        if len(v) > 4:
            raise ValueError("segments must contain at most 4 items")
        return v

    @field_validator("intro", "outro", "segments", mode="after")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        """Clean extra whitespace from text fields."""
        if isinstance(v, str):
            return v.strip()
        return v

    def to_plain_text(self) -> str:
        """
        Convert the script to a single plain text string for TTS.

        Returns:
            Text ready for Edge-TTS input.
        """
        parts = [
            self.intro,
            "",
            "\n\n".join(self.segments),
            "",
            self.outro,
        ]
        return "\n".join(parts)

    def estimated_word_count(self) -> int:
        """
        Calculate approximate word count of the full script.

        Handles punctuation and multiple spaces correctly.

        Returns:
            Total number of words across all fields.
        """
        full_text = f"{self.intro} {' '.join(self.segments)} {self.outro}"
        # Split on whitespace and filter empty strings
        words = re.findall(r"\b\w+\b", full_text)
        return len(words)